In [321]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [322]:
df = pd.read_csv('/Users/jonathanrabbi/Desktop/Data_Analysis_Immo/CSV_Files/Cat_House_details.csv')

In [323]:
df_House=df[df['Type of property']=='house']

X= df_House[['Bedrooms','Bathrooms','Toilets','Surface of the plot']]

y= df_House['Price']

In [324]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [325]:
from xgboost import XGBRegressor

xg_reg=XGBRegressor()

In [326]:
xg_reg.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [327]:
y_pred=xg_reg.predict(X_test)
y_pred

array([ 301742.97,  289739.66,  313357.12,  302794.06,  289739.66,
        592843.2 ,  289739.66,  243052.31,  243052.31,  621626.56,
        815198.3 ,  289739.66,  313394.66,  313394.66,  313394.66,
        258426.88,  289739.66,  313357.12,  243052.31,  289739.66,
        289739.66,  289739.66,  243052.31,  313394.66,  289739.66,
        289739.66,  232604.4 ,  289739.66,  289739.66,  289739.66,
        289739.66,  313394.66,  243052.31,  325131.4 ,  325131.4 ,
        325131.4 ,  325131.4 ,  232604.4 ,  285301.03,  313394.66,
        249262.31,  249262.31,  243052.31,  592843.2 ,  201588.12,
        232604.4 ,  282913.28,  243052.31,  302794.06,  400369.12,
        243052.31,  243052.31,  302794.06,  546004.1 ,  313357.12,
        289739.66,  289739.66,  243052.31,  592843.2 ,  289739.66,
        289739.66,  232604.4 ,  302794.06,  289739.66,  325131.4 ,
        546004.1 ,  289739.66,  289739.66,  243052.31,  232604.4 ,
        243052.31,  285301.03,  289739.66,  243052.31,  870101

In [328]:
from sklearn.metrics import mean_squared_error

mse=mean_squared_error(y_test,y_pred)
print('MSE: %0.2f' %(mse))

MSE: 58367714693.30


In [329]:
rmse=np.sqrt(mse)
rmse

241594.11146239343

In [330]:
print('RMSE: %0.2f' %(rmse))

RMSE: 241594.11


In [331]:
from sklearn.model_selection import cross_val_score

model = XGBRegressor(objective='reg:squarederror')

In [332]:
scores =cross_val_score(model, X,y, 
                        scoring="neg_mean_squared_error",
                        cv=10)

scores

array([-4.65839444e+10, -8.45352027e+10, -5.32805517e+10, -5.57680506e+10,
       -7.10766737e+10, -2.79933291e+11, -2.61503829e+10, -3.23635660e+10,
       -3.41262822e+10, -6.97092148e+10])

In [333]:
rmse = np.sqrt(-scores)

rmse

array([215833.14013934, 290749.38124995, 230825.8037581 , 236152.60019148,
       266602.08874957, 529087.22460116, 161710.80014946, 179898.76588384,
       184733.00233333, 264025.02688445])

In [334]:
print(xg_reg.score(X_train,y_train))
print(xg_reg.score(X_test,y_test))

0.410609358863554
0.36416842025374996
