In [181]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [182]:
df = pd.read_csv('/Users/jonathanrabbi/Desktop/Data_Analysis_Immo/CSV_Files/Cat_House_details.csv')

In [183]:
df_House=df[df['Type of property']=='house']

X= df_House[['Bedrooms','Bathrooms','Toilets','Surface of the plot']]

y= df_House['Price']

In [184]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [185]:
from xgboost import XGBRegressor

xg_reg=XGBRegressor()

In [186]:
xg_reg.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [187]:
y_pred=xg_reg.predict(X_test)
y_pred

array([161355.42, 551429.4 , 417769.22, ..., 515807.47, 699646.25,
       351883.44], dtype=float32)

In [188]:
from sklearn.metrics import mean_squared_error

mse=mean_squared_error(y_test,y_pred)
print('MSE: %0.2f' %(mse))

MSE: 47449985335.73


In [189]:
rmse=np.sqrt(mse)
rmse

217830.17544806108

In [190]:
print('RMSE: %0.2f' %(rmse))

RMSE: 217830.18


In [191]:
from sklearn.model_selection import cross_val_score

model = XGBRegressor(objective='reg:squarederror')

In [192]:
scores =cross_val_score(model, X,y, 
                        scoring="neg_mean_squared_error",
                        cv=10)

scores

array([-3.86686201e+10, -9.67096632e+10, -1.03045334e+11, -1.18710080e+11,
       -1.35044473e+11, -6.57837538e+10, -8.05686918e+10, -5.05832482e+10,
       -5.36233754e+10, -1.03078910e+11])

In [193]:
rmse = np.sqrt(-scores)

rmse

array([196643.38295432, 310981.77307349, 321006.74996935, 344543.29260161,
       367483.97584909, 256483.43767889, 283846.24672976, 224907.19906842,
       231567.21574711, 321059.0441903 ])

In [194]:
print(xg_reg.score(X_train,y_train))
print(xg_reg.score(X_test,y_test))

0.9308901945113759
0.3831321641480052
